#!/opt/bin/php
<?php
declare(strict_types=1);

use App\ReactHandler;
use App\ReactRuntime;
use React\EventLoop\StreamSelectLoop;

ini_set('display_errors', '1');
error_reporting(E_ALL);

$appRoot = getenv('LAMBDA_TASK_ROOT');

require $appRoot . '/vendor/autoload.php';

$loop = new StreamSelectLoop();
$runtime = new ReactRuntime($loop);
$container = require 'config/container.php';

$handler = getenv('_HANDLER');

if (! $container->has($handler)) {
    $runtime->failInitialization("Handler `$handler` doesn't exist");
}
$reactPhpHandler = new ReactHandler($loop, $container->get($handler));

echo 'React PHP Event Loop Initialized';

$callback = static function() use ($runtime, $reactPhpHandler, &$callback) {
    $runtime->processNextEvent($reactPhpHandler, $callback);
};

$loop->futureTick($callback);

$loop->run();
